language: cpp
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install cmake libgtest-dev
- sudo apt-get install doxygen
- sudo apt-get install graphviz
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- cd $TRAVIS_BUILD_DIR
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen Doxyfile
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local-dir: html
    on:
    branch: master
  - provider: script
    skip_cleanup: true
    script:
  - curl -T print_ip-1.1.$TRAVIS_BUILD_NUMBER-Linux.deb -uperepiskass:$BINTRAY_API_KEY "https://api.bintray.com/content/perepiskass/Print_IP/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-1.1.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"